// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPrNFzAWFlwY5UTEPzBS71g5qg_c8_3EE',
    appId: '1:160417660222:web:23b07a181921c50996406f',
    messagingSenderId: '160417660222',
    projectId: 'leave-management-516b3',
    authDomain: 'leave-management-516b3.firebaseapp.com',
    storageBucket: 'leave-management-516b3.firebasestorage.app',
    measurementId: 'G-G1KHLTSRTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQOuEKrk3ZKk16OnG2sbB2boI20vClzgk',
    appId: '1:160417660222:android:cbbef614a71b898b96406f',
    messagingSenderId: '160417660222',
    projectId: 'leave-management-516b3',
    storageBucket: 'leave-management-516b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6OcyW1-hWdpDnvYnZdFyPZIM2VJBMJHc',
    appId: '1:160417660222:ios:ac02215556b69ba696406f',
    messagingSenderId: '160417660222',
    projectId: 'leave-management-516b3',
    storageBucket: 'leave-management-516b3.firebasestorage.app',
    iosBundleId: 'com.example.leaveManagement',
  );
}
